### ISSUE TITLE
GUI ImportError

### ISSUE THREAD

**Issue by caitlingilbert** [brainglobe/brainrender#170]
Hi! After a fresh install of brainrender in a new env (I've tried this in py3.7, 3.6, 3.8 envs) with PySide2 (on a Mac/BigSur), I am attempting to run the brainrender-gui call and keeping hitting the following error:

`Traceback (most recent call last):
  File "/Users/caitlingilbert/opt/anaconda3/envs/py37/bin/brainrender-gui", line 5, in <module>
    from brainrender.gui.__init__ import clilaunch
  File "/Users/caitlingilbert/opt/anaconda3/envs/py37/lib/python3.7/site-packages/brainrender/gui/__init__.py", line 5, in <module>
    from brainrender.gui.app import App
  File "/Users/caitlingilbert/opt/anaconda3/envs/py37/lib/python3.7/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/caitlingilbert/opt/anaconda3/envs/py37/lib/python3.7/site-packages/brainrender/gui/app.py", line 9, in <module>
    from brainrender import Scene
ImportError: cannot import name 'Scene' from 'brainrender' (unknown location)
`
Not sure if it's something is wrong with my install, a version issue, or something else I'm doing!

**Comment by adamltyson** [comment]
@FedeClaudi I was having trouble with this earlier, even using the Python API.

**Comment by FedeClaudi** [comment]
Hi, thanks for the report.
I had messed up the packaging, installing `pip install brainrender==2.0.4.0` should fix that

**Comment by caitlingilbert** [comment]
Thanks, @FedeClaudi! Works for me now.
