### ISSUE TITLE
Coordinates seem to be wrongly read from MouseLight neuron loaded as .swc

### ISSUE THREAD

**Issue by harshk95** [brainglobe/brainrender#181]
Hi,
I tried to run the neruons.py example from the examples folder and downloaded the .swc file for one of the neurons in the Mouse Light database from the MouseLight neuron browser. However, the neuron is strangely oriented and seems to be switching 2 of the coordinates. The ID of the neuron shown in the figure attached is AA1544.
This has been run on a Windows machine with the latest version of brainrender on Python 3.7
![image](https://user-images.githubusercontent.com/42764867/144130825-7c751e45-e9b5-434f-8439-b8f5336f5825.png)

Any help is much appreciated!
Thanks!

**Comment by harshk95** [comment]
Additionally, upon running the mouselight api to fetch the metadata from neuron.py , I get the following error:

> Querying MouseLight API...
>      ... fetched metadata for 1110 neurons in 2.03s
> allen mouse atlas (res. 25um)
> From: http://www.brain-map.org (Wang et al 2020, https://doi.org/10.1016/j.cell.2020.04.007 )
>         ... selected 257 neurons out of 1110
> Downloading neurons
> Working... ---------------------------------------- 100% 0:00:00
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pyinspect\utils.py", line 140, in read_single_line
>     for i, line in enumerate(f):
>   File "C:\Users\kanohars\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1470: character maps to <undefined>
> 
> Original exception was:
> Traceback (most recent call last):
>   File "neurons.py", line 25, in <module>
>     neurons = scene.add(*make_neurons(*neurons, neurite_radius=12))
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\brainrender\actors\neurons.py", line 31, in make_neurons
>     for n in neurons
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\brainrender\actors\neurons.py", line 31, in <listcomp>
>     for n in neurons
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\brainrender\actors\neurons.py", line 69, in __init__
>     mesh = self._from_morphapi_neuron(neuron)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\brainrender\actors\neurons.py", line 81, in _from_morphapi_neuron
>     soma_radius=self.soma_radius,
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\morphapi\morphology\morphology.py", line 256, in create_mesh
>     actors.append(Tube(coords, r=neurite_radius))
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\vedo\shapes.py", line 1328, in __init__
>     if len(p)==3:
> TypeError: object of type 'numpy.float64' has no len()

**Comment by FedeClaudi** [comment]
Hi, 

Is this still an issue? Is the problem there with all neurons or particular ones?

**Comment by harshk95** [comment]
This issue persists for neurons from other datasets that are now available and has to do with the Neuron actor hardcoding the `invert_dims = True `
in MorphoNeuron form the morphapi.morhology.morpholgy

The issue can be resolved by allowing the user to set the invert_dims when creating the Brainrender Neuron actor

**Comment by IgorTatarnikov** [comment]
Hi @harshk95, thanks for your suggestion! The `invert_dims` parameter should now be exposed in the `Neuron` constructor.

This fix is now in the latest version of `brainrender` (update with `pip install brainrender -U`).
