### ISSUE TITLE
Cannot from brainrender import Scene 

### ISSUE THREAD

**Issue by damingli09** [brainglobe/brainrender#190]
Hi, I have installed brainrender successfully but it reports error when I tried "from brainrender import Scene". I'm not sure if this is due to any package conflicts (my neurom package version is 1.4.20 now). The error is shown below. Thanks!

>>> from brainrender import Scene
Error in sys.excepthook:
Traceback (most recent call last):
  File "//anaconda3/lib/python3.7/site-packages/pyinspect/exceptions.py", line 146, in excepthook
    emanager.render_error()
  File "//anaconda3/lib/python3.7/site-packages/pyinspect/exceptions.py", line 83, in render_error
    relevant_only=self.relevant_only,
  File "//anaconda3/lib/python3.7/site-packages/pyinspect/_exceptions.py", line 291, in inspect_traceback
    eline = read_single_line(fpath, f.f_lineno - 1)
  File "//anaconda3/lib/python3.7/site-packages/pyinspect/utils.py", line 136, in read_single_line
    "When reading a single line from file: the file doesnt exist!"
FileExistsError: When reading a single line from file: the file doesnt exist!

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Scene' from 'brainrender' (//anaconda3/lib/python3.7/site-packages/brainrender/__init__.py)

**Comment by m-col** [comment]
I'm also getting this. How did you resolve it?

**Comment by FedeClaudi** [comment]
Hi sorry @damingli09 I completely missed this issue.

Can you guys five me more details here? Did you try a fresh install? Which python version? Did you try in scripts or just notebooks? What happens if you do `from brainrender.scene import Scene`?

**Comment by m-col** [comment]
OK, got it fixed. It was my bad - I had an old version of brainrender being imported instead of my pip installed version.
