### ISSUE TITLE
ValueError: allen_mouse_25um is not a valid atlas name! Exception ignored in: <function Scene.__del__ at 0x000002889456ED30>

### ISSUE THREAD

**Issue by saulgoodenough** [brainglobe/brainrender#228]
Hi, 

I just got the error as follows when I tried to run the example, and it seems that the problem is related to the brainglobe version. But I installed the newest version.

```
from brainrender import Scene

from rich import print
from myterial import orange
from pathlib import Path

print(f"[{orange}]Running example: {Path(__file__).name}")

# Create a brainrender scene using the zebrafish atlas
scene = Scene(title="Mouse")

# Render!
scene.render()
```

```┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ C:\Users\Administrator\anaconda3\envs\env_py\lib\site-packages\brainrende │
│ r\atlas.py:26 in __init__                                                   │
│                                                                             │
│    23 │   │   logger.debug(f"Generating ATLAS: {atlas_name}")               │
│    24 │   │                                                                 │
│    25 │   │   try:                                                          │
│ >  26 │   │   │   super().__init__(                                         │
│    27 │   │   │   │   atlas_name=atlas_name, print_authors=False            │
│    28 │   │   │   )                                                         │
│    29 │   │   except TypeError:                                             │
└─────────────────────────────────────────────────────────────────────────────┘
TypeError: __init__() got an unexpected keyword argument 'print_authors'

During handling of the above exception, another exception occurred:

┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ D:/Research_programs/3d_brain_view/mouse/test_brainrender.py:16 in     │
│ <module>                                                                    │
│                                                                             │
│   13 print(f"[{orange}]Running example: {Path(__file__).name}")             │
│   14                                                                        │
│   15 # Create a brainrender scene using the zebrafish atlas                 │
│ > 16 scene = Scene(title="Mouse")                                           │
│   17                                                                        │
│   18 # Render!                                                              │
│   19 scene.render()                                                         │
│                                                                             │
│ C:\Users\Administrator\anaconda3\envs\env_py\lib\site-packages\brainrende │
│ r\scene.py:55 in __init__                                                   │
│                                                                             │
│    52 │   │   self.actors = []  # stores all actors in the scene            │
│    53 │   │   self.labels = []  # stores all `labels` actors in scene       │
│    54 │   │                                                                 │
│ >  55 │   │   self.atlas = Atlas(atlas_name=atlas_name)                     │
│    56 │   │                                                                 │
│    57 │   │   self.screenshots_folder = (                                   │
│    58 │   │   │   Path(screenshots_folder)                                  │
│                                                                             │
│ C:\Users\Administrator\anaconda3\envs\env_py\lib\site-packages\brainrende │
│ r\atlas.py:31 in __init__                                                   │
│                                                                             │
│    28 │   │   │   )                                                         │
│    29 │   │   except TypeError:                                             │
│    30 │   │   │   # The latest version of BGatlas has no print_authors argu │
│ >  31 │   │   │   super().__init__(atlas_name=atlas_name)                   │
│    32 │                                                                     │
│    33 │   @property                                                         │
│    34 │   def zoom(self):                                                   │
│                                                                             │
│ C:\Users\Administrator\anaconda3\envs\env_py\lib\site-packages\bg_atlasap │
│ i\bg_atlas.py:78 in __init__                                                │
│                                                                             │
│    75 │   │   # Look for this atlas in local brainglobe folder:             │
│    76 │   │   if self.local_full_name is None:                              │
│    77 │   │   │   if self.remote_version is None:                           │
│ >  78 │   │   │   │   raise ValueError(f"{atlas_name} is not a valid atlas  │
│    79 │   │   │                                                             │
│    80 │   │   │   rprint(                                                   │
│    81 │   │   │   │   f"[magenta2]Bgatlas_api: {self.atlas_name} not found  │
└─────────────────────────────────────────────────────────────────────────────┘
ValueError: allen_mouse_25um is not a valid atlas name!
Exception ignored in: <function Scene.__del__ at 0x000002889456ED30>
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\env_py\lib\site-packages\brainrender\scene.py", line 102, in __del__
    self.close()
  File "C:\Users\Administrator\anaconda3\envs\env_py\lib\site-packages\brainrender\render.py", line 281, in close
    self.plotter.close()
AttributeError: 'NoneType' object has no attribute 'close'

Process finished with exit code 1
```

**Comment by saulgoodenough** [comment]
Finally I found it a internet connection issue. Solved
