### ISSUE TITLE
BUG: Cannot install brainrender using pip

### ISSUE THREAD

**Issue by shunnnli** [brainglobe/brainrender#237]
**Describe the bug**
Pip install brainrender output's an error when trying to build wheel
I'm using an M2 max macbook pro installed macOS 13.4.1 (c), the conda environment is installed using following command: conda create --name brainrender python=3.8 -y

**Expected behavior**

**Screenshots**
(brainrender) shunli@shuns-mbp ~ % pip install brainrender
Collecting brainrender
  Using cached brainrender-2.0.5.5-py3-none-any.whl (113 kB)
Collecting numpy (from brainrender)
  Using cached numpy-1.24.4-cp38-cp38-macosx_11_0_arm64.whl (13.8 MB)
Collecting pandas (from brainrender)
  Using cached pandas-2.0.3-cp38-cp38-macosx_11_0_arm64.whl (10.7 MB)
Collecting vedo==2021.0.5 (from brainrender)
  Using cached vedo-2021.0.5.tar.gz (9.3 MB)
  Preparing metadata (setup.py) ... done
Collecting k3d==2.7.4 (from brainrender)
  Using cached K3D-2.7.4-py2.py3-none-any.whl (12.0 MB)
Collecting msgpack (from brainrender)
  Using cached msgpack-1.0.5-cp38-cp38-macosx_11_0_arm64.whl (68 kB)
Collecting pyyaml>=5.3 (from brainrender)
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/shunli/miniconda3/envs/brainrender/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/shunli/miniconda3/envs/brainrender/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/shunli/miniconda3/envs/brainrender/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/zd/cj43fhkd6pddg_t4m2l4bhth0000gn/T/pip-build-env-qtzkdy9b/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/zd/cj43fhkd6pddg_t4m2l4bhth0000gn/T/pip-build-env-qtzkdy9b/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/zd/cj43fhkd6pddg_t4m2l4bhth0000gn/T/pip-build-env-qtzkdy9b/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "/private/var/folders/zd/cj43fhkd6pddg_t4m2l4bhth0000gn/T/pip-build-env-qtzkdy9b/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/zd/cj43fhkd6pddg_t4m2l4bhth0000gn/T/pip-build-env-qtzkdy9b/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/zd/cj43fhkd6pddg_t4m2l4bhth0000gn/T/pip-build-env-qtzkdy9b/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/zd/cj43fhkd6pddg_t4m2l4bhth0000gn/T/pip-build-env-qtzkdy9b/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/zd/cj43fhkd6pddg_t4m2l4bhth0000gn/T/pip-build-env-qtzkdy9b/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/private/var/folders/zd/cj43fhkd6pddg_t4m2l4bhth0000gn/T/pip-build-env-qtzkdy9b/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/zd/cj43fhkd6pddg_t4m2l4bhth0000gn/T/pip-build-env-qtzkdy9b/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 314, in run
          self.find_sources()
        File "/private/var/folders/zd/cj43fhkd6pddg_t4m2l4bhth0000gn/T/pip-build-env-qtzkdy9b/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
          mm.run()
        File "/private/var/folders/zd/cj43fhkd6pddg_t4m2l4bhth0000gn/T/pip-build-env-qtzkdy9b/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/private/var/folders/zd/cj43fhkd6pddg_t4m2l4bhth0000gn/T/pip-build-env-qtzkdy9b/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/zd/cj43fhkd6pddg_t4m2l4bhth0000gn/T/pip-build-env-qtzkdy9b/overlay/lib/python3.8/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "/private/var/folders/zd/cj43fhkd6pddg_t4m2l4bhth0000gn/T/pip-build-env-qtzkdy9b/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/zd/cj43fhkd6pddg_t4m2l4bhth0000gn/T/pip-build-env-qtzkdy9b/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 204, in get_source_files
        File "/private/var/folders/zd/cj43fhkd6pddg_t4m2l4bhth0000gn/T/pip-build-env-qtzkdy9b/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

The following is the package installed after running conda create:
I updated wheel and setuptools already but still failed to install
![image](https://github.com/brainglobe/brainrender/assets/44044548/c3f64022-2b80-4ded-bb3a-14421c41f513)

**Comment by alessandrofelder** [comment]
Thanks a lot for reporting this @shunnnli 

Installation with pip on the latest development branch `mega-fix` now works for me on my Mac M2 with
```
conda create -n new-environment python=3.11
conda install hdf5
pip install git+https://github.com/brainglobe/brainrender@mega-fix
```
`hdf5` is needed because of a [known `pytables` issue, I think](https://github.com/brainglobe/brainglobe-segmentation/issues/145#issuecomment-1814207696). We will update the installation instructions as part of https://github.com/brainglobe/brainrender/issues/253 to clarify this.

We will make a new release very soon (so it's installable from pypi) but if you could double-check and report back whether it works for you, that would be great.
